### ISSUE TITLE
Example how to use content_scripts

### ISSUE THREAD

**Issue by jazeonli** [dart-gde/chrome.dart#228] opened 2015-07-13 12:44 UTC
Please provide an example on using content script for Chrome Extensions written in Dart.

Content script written in Dart doesn't execute. The 'main' function in the content script dart file does not seem to run:

```dart
void main() {
  print('Start: content-script');
}
```

Using background script works:

```dart
void main() {
  print('Start: background');
}
```

Manifest.json:

```json
  "background": {
    "scripts": ["background.dart.js"]
  },
  "content_scripts": [
    {
      "matches": ["http://*/*", "https://*/*"],
      "js": ["content.dart.js"],
      "css": ["css/style.css"],
      "run_at": "document_start"
    }
  ],
```

**Comment by jazeonli** [comment] 2015-07-14 08:07
I did some debugging and I believe there is a bug in dart2js for the chrome.dart.

At the end of the content.dart.js is the code that starts the main function. I added **();** to both functions and the main function was called after the change.

Before the change console.log calls from 1-5 were displayed, but not #6. After the change all console.log calls from 1-6 are called and the print() in main function is displayed.

  // BEGIN invoke [main].
  (function(callback) {
    console.log('Begin invoke main 1');
    if (typeof document === "undefined") {
      callback(null);
      return;
    }
    console.log('Begin invoke main 2');
    if (document.currentScript) {
      callback(document.currentScript);
      return;
    }
    console.log('Begin invoke main 3');
    var scripts = document.scripts;
    function onLoad(event) {
      for (var i = 0; i < scripts.length; ++i)
        scripts[i].removeEventListener("load", onLoad, false);
      callback(event.target);
    }
    console.log('Begin invoke main 4');
    for (var i = 0; i < scripts.length; ++i)
      scripts[i].addEventListener("load", onLoad, false);
    console.log('Begin invoke main 5');
  })**();**    // <-- Added
  (function(currentScript) {
    console.log('Begin invoke main 6');
    init.currentScript = currentScript;
    if (typeof dartMainRunner === "function")
      dartMainRunner(T.main, []);
    else
      T.main([]);
  })**();**    // <-- Added
  // END invoke [main].

**Comment by zoechi** [comment] 2015-07-14 08:11
If you enclose code in three backticks \`\`\`your code\`\`\` it becomes more readable
with 
\`\`\`dart
your code
\`\`\`
you get even Dart syntax highlighting

**Comment by adambender** [comment] 2015-07-14 14:23
jazeonli do you happen to have the sample app (entire dart project) exhibiting the same behavior? It would be good to see how you are building your project. 

One theory I have without looking at the code is based in my past my experience with dart2js. IIRC dart2js only allows one main method to be setup to 'autorun' per project. In the case of chrome extensions and chrome apps I have often had to build either a separate app for each page, or, make my main a bootstrapping function which figures out how to run itself based on how it was called.

**Comment by jazeonli** [comment] 2015-07-14 14:34
Hi adambender,

Full sample code is at dartlang forum (couldn't upload it here): https://groups.google.com/a/dartlang.org/forum/#!topic/misc/CFNU-jmCTiU

I was thinking in the same direction regarding only one main method. However it is interesting how adding (); solves the problem for content script and still allows background script to run. It would be easy to add this change with a transformer.

**Comment by adambender** [comment] 2015-07-15 15:15
After reading that thread it appears the issue is actually with dart2js and not chrome.dart are you of the same opinion?

**Comment by jazeonli** [comment] 2015-07-15 16:25
Depending on how you look at it. dart2js produces the same code for background and content script. The one for the background script works fine (so there is probably no bug in dart2js).

Since only content script doesn't work and it is specific to Chrome extension, chrome.dart could solve this with an updated transformer. It would only have to change the code for the content script main function to run.

**Comment by jazeonli** [comment] 2015-07-15 16:29
See also Florian Loitsch post in dartlang forum for the great explanation and the solution:

https://groups.google.com/a/dartlang.org/forum/#!topic/misc/CFNU-jmCTiU

**Comment by adambender** [comment] 2015-07-16 14:35
So I took another look at that thread and followed it up with a quick conversation with Florian. He and I both agree that this really is a bug in dart2js and that the best course of action is to let his patch land. I understand the inconvenience you are experiencing Im just not sure chrome.dart is the right project to address it. Fixing this issue by adding a transformer to chrome.dart, while possible, isn't really consistent with the goal of the project. For starters, transforming dart2js output is not recommended as it is not guaranteed to be stable in anyway. Without an AST or guaranteed syntax usage the best you can do is a regex which will become very error prone. Most importantly, Im opposed introducing and maintaining a new feature that is a work around for a bug that is being fixed in another project. It would be obsolete before the paint really dried. 

Im going to go ahead and close this issue.

**Closed by adambender** 2015-07-16 14:35 UTC

**Comment by jazeonli** [comment] 2015-07-16 15:10
I agree. I was thinking about using the transformer only as an interim fix until the real cause is fixed. Thank you for your help.
